# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  version: '0.2.2'

steps:
- script: dotnet build src/Cake.Watch/Cake.Watch.csproj
  displayName: "Build Project"

- script: dotnet pack src/Cake.Watch/Cake.Watch.csproj --configuration $(buildConfiguration) /p:PackageVersion=$(version) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet'

- task: PublishBuildArtifacts@1

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'