# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  version: '0.2.2'

steps:
- script: dotnet pack src/Cake.Watch/Cake.Watch.csproj --configuration $(buildConfiguration) /p:PackageVersion=$(version)
  displayName: 'dotnet pack $(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGet'
    versioningScheme: byEnvVar
    versionEnvVar: version